### ISSUE TITLE
Reliable way to listen to a runner `ready` event

### ISSUE THREAD

**Issue by iamdustan** [uxebu/bonsai#100]
There is no reliable way to detect when a runner environment and all plugins are loaded and ready to go. The `bonsai.run().on(`start`)` event behaves inconsistently if there are plugins to load.

I have created two demos to show the issue. Both demos do the exact same thing with the only change to the second demo is loading in a plugin.

**Demo 1. Expected behavior.**
http://jsfiddle.net/LAuFB/10/

**Demo 2. Message sent at `stage.on('start')` never received**
http://jsfiddle.net/LAuFB/9/

I started digging into the code and got in so far as  these two bits: https://github.com/uxebu/bonsai/blob/master/src/renderer/renderer_controller.js#L206
https://github.com/uxebu/bonsai/blob/master/src/renderer/renderer_controller.js#L60

A few solutions I have considered are:
1. Don’t fire the `start` event until all plugins are loaded.
2. Add a `ready` event once all plugins are loaded.
3. do a `stage.once('render', function () { stage.sendMessage('ready'); })` in userland (don’t fix)

**Comment by davidaurelio** [comment]
Thanks for reporting, we will fix that with solution 1, I guess

**Comment by iamdustan** [comment]
Fixed by #158. Closing.
