### ISSUE TITLE
IE8 javascript errors

### ISSUE THREAD

**Issue by kmturley** [uxebu/bonsai#113]
http://demos.bonsaijs.org/demos/blobs/index.html

SCRIPT445: Object doesn't support this action 
bonsai-0.4.0.min.js, line 92 character 357
SCRIPT5009: 'bonsai' is undefined 
index.html, line 184 character 3

Also there is now browser supported list on your site

**Comment by basecode** [comment]
Thanks for your feedback! Unfortunately IE8 is not supported. Although Bosai's architecture probably wouldn't prevent us from hocking in an IE8-friendly Renderer (e.g. using VML) we're not planing to do that right now.

> Also there is now browser supported list on your site

Please visit http://docs.bonsaijs.org/#browser_support to see the list of supported browsers. But yes, it would make sense to put the infos on Bonsai's homepage as well.
