### ISSUE TITLE
Real number framerates

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#114]
Setting it to `0.5` fps causes it to go quite fast.

**Comment by basecode** [comment]
Thanks for the pull-request @davidaurelio! What's exactly the benefit of allowing fractional numbers? What is a half frame per second? Wouldn't it be sufficient to only allow a minimum framerate of 1?

**Comment by davidaurelio** [comment]
> What's exactly the benefit of allowing fractional numbers? 

That frame rates are not tied to _whole-number-to-second-ratios._

> What is a half frame per second?

One frame every two seconds.

> Wouldn't it be sufficient to only allow a minimum framerate of 1?

Why should we restrict it in such a way?

**Comment by wolframkriesing** [comment]
how often did i wish for fps=0.1 to really watch what happens in slow motion, nice way of "debugging" or getting insight into a movie

**Comment by basecode** [comment]
> Why should we restrict it in such a way?

You're right. The restriction doesn't make sense.
