### ISSUE TITLE
getComputed() wrong with negative values

### ISSUE THREAD

**Issue by wolframkriesing** [uxebu/bonsai#116]
The following 

``` js
var rect = new Rect(100, 100, -100, -100)
  .attr({fillColor: 'red'})
  .addTo(stage);

console.log(rect.attr('x'));
console.log(rect.attr('y'));
console.log(rect.getComputed('width'));
console.log(rect.getComputed('height'));
```

prints four times, 100, though x+y should be 0

**Comment by iamdustan** [comment]
Wouldn’t that end up being a Rectangle that just had it’s origin point in the visible bottom right corner? I would expect the bounding box of that element to be `x1: 0, y1: 0, x2: 100, y2: 100`? I don’t know if I would expect the getComputed('width') to be `100` or `-100`.

**Comment by wolframkriesing** [comment]
yep, that would make most sense but might have influence on any further
operations, since the origin was moved
i actuakly thought the computed width and height should -100
i let u guys figure out, for my use case both works  but thats not what
counts, lets find the right solution!
Am 12.10.2012 02:26 schrieb "Dustan Kasten" notifications@github.com:

**Comment by davidaurelio** [comment]
> though x+y should be 0

No, they should equal the values you’ve passed to the constructor, i.e. `100`. The signature of `Rect` is `x, y, width, height`.

The _computed_ left/top values should be 0, and that’s what `getComputed` returns for them

``` js
>>> rect.getComputed('size');
{ top: 0, right: 100, bottom: 100, left: 0, width: 100, height: 100 }
```

> I don’t know if I would expect the getComputed('width') to be 100 or -100

We are going with `100`, because it felt more intuitive to return the visible size. Please reopen if this feels wrong.

**Comment by wolframkriesing** [comment]
I understand the width/height=100, but that makes the x,y,width,height tuple useless, and that was the trap i stepped in. didnt even know about "size". if we wanna stick to it we might get some clearer naming ... dont know how, but the current solution is very irritating

**Comment by iamdustan** [comment]
@wolframkriesing agreed that the current `getComputed` is a tricky road to travel at present. Does the discussion at #74 address this as well?

**Comment by davidaurelio** [comment]
- Yes, “size” is not good, see #74.
- Yes, the tuple `[attr('x'), attr('y'), getComputed('width'), getComputed('height')]` tuple is not really useful; should we document that explicitly?

**Comment by davidaurelio** [comment]
Maybe the docs should also state that `getComputed` is not the cheapest of operations and that if multiple values are needed, retrieving the whole struct is totally worth it.

**Comment by wolframkriesing** [comment]
imho documenting is the second best solution, getting it intuitively
correct the first best ;)
imho getcomputed(x) is supposed to be 0 here, because thats where the rect
is positioned
Am 12.10.2012 16:03 schrieb "David Aurelio" notifications@github.com:

**Comment by davidaurelio** [comment]
yes, `'x'` and `'y'` aliases for `'left'` and `'top'` are coming.

**Comment by iamdustan** [comment]
Whoa. I just realized I was totally misunderstanding the core issue of this. The `x+y should be 0` reference threw me off.

In this case I would agree with @wolframkriesing that the computed x and y should include what is currently displayed, and not what was passed in initially to the constructor. With `getComputed` I would expect the results to reflect what is currently on the screen.

**Comment by wolframkriesing** [comment]
thx dustan, i think u found the right wording ;) percect to go into the docs
Am 12.10.2012 16:12 schrieb "Dustan Kasten" notifications@github.com:

**Comment by davidaurelio** [comment]
> Whoa. I just realized I was totally misunderstanding the core issue of this. The x+y should be 0 reference threw me off.

Yes, absolutely, but the initial example used `attr('x/y')`. This should not return the computed value, imho.

**Comment by iamdustan** [comment]
> Maybe the docs should also state that getComputed is not the cheapest of operations and that if multiple values are needed, retrieving the whole struct is totally worth it.

could `getComputed` **always** return an object of values? If it’s expensive and we need to compute most/all of the values anyway; why not just return the entire boundingbox object everytime and let the user grab the exact value they need if only one?

```
var rect = new Rect(100, 100, -100, -100)
  .attr({fillColor: 'red'})
  .addTo(stage);

// rect.getComputed(); ==> { top: 0, left: 0, width: 100, height: 100 }
// rect.getComputed().width; ==> 100
// rect.getComputed().height; ==> 100
```

**Comment by davidaurelio** [comment]
I like that solution!

**Comment by iamdustan** [comment]
:thumbsup:

**Comment by wolframkriesing** [comment]
will it never return any other values? if so, we should even rename it to
getBoundingBox() which is more explicit
Am 12.10.2012 16:17 schrieb "Dustan Kasten" notifications@github.com:
