### ISSUE TITLE
Flickering Animation with "elasticOut" easing

### ISSUE THREAD

**Issue by basecode** [uxebu/bonsai#117]
See: http://orbit.bonsaijs.org/#new%20Rect(0%2C%200%2C%2099%2C%2099).fill(%22red%22).addTo(stage).animate('1s'%2C%20%7B%0A%20%20fillColor%3A'black'%0A%7D%2C%20%7B%20%0A%20%20easing%3A%20'elasticOut'%0A%7D)%3B%20%20

```
new Rect(0, 0, 99, 99).fill("red").addTo(stage).animate('1s', {
  fillColor:'black'
}, { 
  easing: 'elasticOut'
});  
```

**Comment by padolsey** [comment]
I think this is expected. An elastic easing function goes beyond the 'to' value, which in this case is black. Since you can't go 'beyond' black it just goes to black and then back to red and then back to black and then back to a slightly darker red etc.

What are you expecting?

**Comment by basecode** [comment]
I guess I was expecting some magic ;) Thanks for clarification!
