### ISSUE TITLE
Weird glitches with groups missing width or height

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#118]
Try

``` js
var g = new Group().attr({x:100,y:100,width:100,height:200}).addTo(stage);
var x = 400;
new Rect(109, 100, 110, 100).fill('random').addTo(g);
new Circle(65,520,50).fill('blue').animate('1s', {x:300}).addTo(stage);
```

Now try to remove the width or height property from the group completely (items blow up and lose color, items dispositioned, wtf?).

Now remove them both (color disappears, items dispositioned, wtf?). It crashes in another instance of orbit, so either way, something's funky.

**Comment by davidaurelio** [comment]
Thanks. Looks evil

**Comment by padolsey** [comment]
I can't reproduce this. Am I supposed to be using orbit? Also, Groups don't have width or height attributes so I'm curious as to why it's supposed to be having an effect at all.

**Comment by pvdz** [comment]
Repro test case (using orbit on .ux) http://goo.gl/qHurS

Remove height (from group attr) to see glitch. Or instead, add width to see error.

**Comment by pvdz** [comment]
Turns out to be a bug in my development branch. Sorry for the confusion.
