### ISSUE TITLE
zero alpha in rgba interpreted as 255

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#119]
`strokeColor: 'rgba(0,0,0,1)'` gives a opaque stroke, strokeColor: 'rgba(0,0,0,0)' gives a transparent stroke but should be completely opaque (even more so than 1).

**Comment by padolsey** [comment]
This should fix it: https://github.com/uxebu/bonsai/commit/3678371d48ae0bf49e608f3a3fda421d9d308f37

Now any values over 1 will be assumed to be 1 and any values below 0 will be assumed to be 0.

**Comment by pvdz** [comment]
cheers
