### ISSUE TITLE
export serialized SVG content

### ISSUE THREAD

**Issue by rsaccon** [uxebu/bonsai#125]
is there a way to obtain the currently rendered SVG content as a text string ? If not, this is an enhancement request (and if that is not on your roadmap, I am interested  to investigate and if possible for me, to implement it). Here my use case: the SVG content I load as <code>data:image/svg+xml</code> into an image, and that I load into a canvas. I am currently using these technique, to load HTML as SVG foreign object into an image and then into canvas and an example usage for this is to create thumbnails of web pages.

**Comment by iamdustan** [comment]
hey @rsaccon. I’m not sure how well getting the svg as a string fits into core with the future plans of non svg-renderers.

Though implementing this in your app code is pretty straightforward.

``` javascript
// setup
var node = document.getElementById('rendered');
bonsai.run(node, 'movie.js')

// Later on. Bonsai wraps it’s svg element with a `div`. Lazily hardcoding it in there.
var svgContents = node.childNodes[0].innerHTML;

// alternatively if you only have one bonsai movie on the screen
var svgContents = document.querySelector('svg[data-bs-id]').parentNode.innerHTML;
```

A few caveats that you may run into:
- if your svg graphic has external images that you want to travel with it, they must be base64 encoded.
- `rgba` (how bonsai renders attributes) is not allowed in the current SVG spec. These should be converted to `rgb`. (see issue #110)
  - To do this yourself in ruby: `svg.gsub! /rgba\(([^\)]*),[\s\d.]+\)/, 'rgb(\1)'`
- the `svg` node must have the following attributes defined `'xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"` (I believe the first one is added by bonsai, but not the second)

Browsers (I have test `webkit` and `moz` the most) are much more lenient about the svg spec than external tools such as Illustrator or Inkscape. The `xmlns:xlink` and CSS3 color modules are direct instances of that.

**Comment by rsaccon** [comment]
iamdustan, thanks a lot, your information is extremely helpful to get my problem solved.

**Comment by iamdustan** [comment]
@rsaccon is it safe to close this issue?

**Comment by rsaccon** [comment]
@iamdustan, yes, thanks
