### ISSUE TITLE
Implement stroke-dasharray

### ISSUE THREAD

**Issue by iamdustan** [uxebu/bonsai#134]
Add `strokeDashArray` to path supported attributes: http://docs.bonsaijs.org/module-path.Path.html

**Documentation**
https://developer.mozilla.org/en-US/docs/SVG/Attribute/stroke-dasharray

**Example**
https://developer.mozilla.org/files/3299/stroke-dasharray.svg

**Comment by basecode** [comment]
Implemented in version 0.4.3.
