### ISSUE TITLE
Point#normalize cleanup

### ISSUE THREAD

**Issue by iamdustan** [uxebu/bonsai#139]
I’ve been dealing with the `Point` object and transform origins and started reading the code and came across this: https://github.com/uxebu/bonsai/blob/master/src/point.js#L61

``` javascript
proto.normalize = function(length) {
  var curlen = sqrt(this.x * this.x + this.y * this.y);
  var fact = length / this.length;
  this.x = this.x * fact;
  this.y = this.y * fact;
  return this;
};
```

I’m not 100% certain what this method is supposed to do, but `curlen` is definitely not used anywhere.

**Comment by klipstein** [comment]
Definitely not. Could you send a pull removing it?
