### ISSUE TITLE
AssetDisplayObject

### ISSUE THREAD

**Issue by basecode** [uxebu/bonsai#16]
To me it looks like a good idea to encapsulate common "asset" functionality in a separate class and let Bitmap/Video/Audio/FontFamily(/Movie?) inherit from it. Also since the AssetLoader is assigned to `_loader` we could try to get rid of as much EventEmitter stuff as possible and instead call instance methods directly. The only callback that is allowed should be the "user" callback (3rd parameter). 

```
function AssetDisplayObject(sharedLoader, resource, callback) {

    // was previously `_loader`
    this._sharedLoader = sharedLoader;

    DisplayObject.call(this);

    if (callback) {
      this.bindAssetCallback(callback);
    }

    this.type = 'AssetDisplayObject';
  }

AssetDisplayObject.prototype.request = function() {…}

```

**Comment by padolsey** [comment]
Fixed in https://github.com/uxebu/bonsai/commit/ef159ea1bf4c4cb6460b8715a925d3f7451c83ed

**Comment by padolsey** [comment]
(Will allow opener to close issue. Please review)
