### ISSUE TITLE
stage.on('pointermove', fn)

### ISSUE THREAD

**Issue by basecode** [uxebu/bonsai#164]
The callback `fn` is supposed to be fired when the pointer moves over the stage but it only fires when the pointer moves over an exisiting DisplayObject on the stage.

```
var tracker = new Path().fill('gray').addTo(stage);

function updateTracker(position) {
  tracker.arc(position.x, position.y, 10, 0, Math.PI*2, 0).closePath();
}

updateTracker({x: 100, y:100});
updateTracker({x: 100, y:200});

stage.on('pointermove', function(e) {
  updateTracker(e);
}); 
```

Expectation: `updateTracker` is supposed to be called when the pointer moves across the stage.

**Comment by davidaurelio** [comment]
I guess you’ve tried this in orbit only.

In orbit, code runs in a submovie with it’s own `stage` variable. Submovies are represented by a `<g>` element within the svg renderer. I guess it is not even desirable to catch all events within a rectangle for such a movie.

Check http://jsfiddle.net/8jVYa/ for an example without submovie.
