### ISSUE TITLE
Point.localToGlobal/globalToLocal

### ISSUE THREAD

**Issue by iamdustan** [uxebu/bonsai#169]
Methods to get what a point is in another matrix space.

Use cases: an element is transformed and you need to do another scale based around an arbitrary point in world coordinates.

The AS2 documentation for `globalToLocal`. http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00001308.html

**Comment by davidaurelio** [comment]
Should this go in `Point.prototype` or in `DisplayObject.prototype`? `Point` has less methods :) Flash has it on `DisplayObject` as well.

I guess I’ll put it there, too, to avoid circular module relationships.
