### ISSUE TITLE
Can't mask a group

### ISSUE THREAD

**Issue by wallynm** [uxebu/bonsai#173]
Hello guys, i'm using bonsaiJS and it's really good, ty for make a good framework like that...
I'm opening this ticket because i don't know another place to get help, i didn't found any group or forum... So, if this is the wrong place, sorry but i tried to find it... :p

Well, my problem it's because i need mask a group and make all of their content to be constrained inside a rect shape, but i already tried and didn't worked...

Also, i have applied drag'n drop into the bitmap to test if he is being constrained by the shape.

That's my example:
http://jsfiddle.net/wallysson/KZvem/

I need to make the Bitmap/Group constrain inside the red shape...  help?

**Comment by davidaurelio** [comment]
It seems to work quite well for me in Chrome. Can you tell me which browser you are using (and on which device)? Maybe it’s an SVG capability problem.

**Comment by wallynm** [comment]
Sorry by posting i here... 
The link on jsfiddle are working quite well... 
I discovered where's myt problem but i don't know how to solve it. It is on my app that i'm building...
This is the link: http://sublimi.com.br/site/capinha

To make it work, you need to load your images clicking on the "Importar da nossa galeria" and login on your Instagram account, them you just drag a image into the bordered square at botttom and the image will be placed there... 

The problem it's because my app won't mask as my example at jsfiddle... I've tryed to copy everything but didn't worked... 

Currently on my app i just import bonsai.min.js and only it. It maybe could be a problem... Actually i don't know the problem.

**Comment by wallynm** [comment]
Problem solved... Once i heard about the problem of use the base tag <base href="http://www.yoururl_website.com"/>, 
Well, i just thought that i would never have a big problem with it, but this tag gave to me a nice headcache... Two days spent to discover that it was blocking bonsai to load additional files to work properly...

I don't know if we could make something to fix it, but a advise to not use it already could help someone on the future...
Ty guys, and sorry about this little thing. 

And ty for the good fw!
