### ISSUE TITLE
Memory leak with resource loader

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#18]
If you keep creating a new `Bitmap` (like in a `setInterval` loop) you'll see memory accumulate, even if you don't assign the result of the `new Bitmap` call. This seems to be the root of at least one memory leak that's causing performance problems for our movies. Especially over time.

**Comment by basecode** [comment]
Related #16

**Comment by padolsey** [comment]
`Bitmap` instances now have a `destroy` method. This has to be called to wipe all references we keep in the renderer related to the asset. See commit: https://github.com/uxebu/bonsai/commit/4f72cfdc846562da119ca498044523df4634a87b

**Comment by pvdz** [comment]
Should update the docs to reflect this requirement.

**Comment by padolsey** [comment]
Updates from Tobi (https://github.com/uxebu/bonsai/pull/26) got rid of the necessity to call `destroy` for Bitmap instances. We've confirmed that the memory leak is gone.

**Comment by pvdz** [comment]
sweet :D
