### ISSUE TITLE
getBoundingBox fails at curved_path.subPathToCurves

### ISSUE THREAD

**Issue by iamdustan** [uxebu/bonsai#190]
When giving an SVG path string to new Path and then attempting to get the bounding box, the world explodes.

See test case on <a href="http://orbit.bonsaijs.org/#a%20%3D%20new%20Path(%22M69.39%2C28.122c0%2C0-11.907-0.074-17.784%2C4.099%20%20%20s-14.581%2C3.852-18.904-0.774c-4.324-4.625-14.904-3.562-17.729-1.608c-2.825%2C1.953%2C11.718%2C0.832%2C16.25%2C4.945%20%20%20c4.532%2C4.114%2C13.538%2C5.154%2C22.051-0.213S69.39%2C28.122%2C69.39%2C28.122L69.39%2C28.122z%20M44.227%2C16.921c0%2C0%2C11.754-1.898%2C25.312%2C0.279%20%20%20c13.558%2C2.178%2C19.209%2C7.941%2C23.78%2C18.994c4.572%2C11.054%2C0.462%2C38.149-11.158%2C51.442s-37.955%2C19.044-51.608%2C9.188%20%20%20C16.899%2C86.967%2C4.761%2C71.042%2C4.037%2C52.006c-0.724-19.036%2C8.527-27.685%2C20.358-31.82c5.438-1.901%2C10.068-2.744%2C13.483-3.1%20%20%20c4.707%2C7.182%2C5.593%2C15.762%2C5.593%2C15.762s1.518%2C0.379-0.021-9.916c-0.297-1.99-0.999-4.051-1.967-6.079%20%20%20C43.253%2C16.815%2C44.227%2C16.921%2C44.227%2C16.921L44.227%2C16.921z%22)%3B%0Aa.fill('%23FED043')%0A%0Aa.addTo(stage)%3B%0A%0Aconsole.log(a.getBoundingBox())%0A%20%20%0A%20%20">orbit</a>

**Comment by basecode** [comment]
Thanks for reporting. `getBoundingBox` looks fine. The parser has an issue with unsupported SVG commands, more precisely "s" and "S". Replacing the unsupported commands should fix that issue. See: #191.

**Comment by iamdustan** [comment]
Roger that. Thanks @basecode
