### ISSUE TITLE
Add support for missing SVG commands

### ISSUE THREAD

**Issue by basecode** [uxebu/bonsai#191]
Commands like "s" and "S" (smooth curve).

**Comment by pvdz** [comment]
Reference: http://stackoverflow.com/questions/15077707/bonsai-js-in-orbit

**Comment by davidaurelio** [comment]
By now, I’d prefer a much smaller set of commands than we already have. In fact, I’d love to have only lines and cubic bezier curves.

**Comment by basecode** [comment]
> I’d love to have only lines and cubic bezier curves

Message protocol spec: +1

This issue mainly discusses the "SVG like" commands parser. `new Path('M0,0S…')` The parser could take care of converting them to lines and cubic bezier curves.

**Comment by davidaurelio** [comment]
agreed
