### ISSUE TITLE
Make use of builtin filters on iOS

### ISSUE THREAD

**Issue by wolframkriesing** [uxebu/bonsai#196]
It seems that since iOS6 there are some filters shipped with webkit per default, would be nice to take advantage of that in bonsai
http://www.youtube.com/watch?v=rXPeWRX-i4w&feature=player_detailpage#t=456s

**Comment by basecode** [comment]
Our SVG Renderer indeed supports SVG Filters and we don't explicitly exclude iOS6. Could you please provide an example what filter exactly doesn't work on iOS6?

**Comment by wolframkriesing** [comment]
i dont know what we are using, but that video showed how to use css filters iirc, if they work with svg i dont know ... just wanted to share this link in case it matters
