### ISSUE TITLE
Default ease for animate

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#20]
`.animate('3s', {opacity:100})` doesn't animate the object (with `opacity` set to `0`) but immediately show it. The animation works when I explicitly define the easing function to use. I believe a default easing function is missing.

**Comment by padolsey** [comment]
Seems to work fine: http://jsbin.com/ewadir/1/edit

Code used to check:

``` js
new Rect(0, 0, 100, 100).fill('red').addTo(stage)
  .attr('opacity', 0)
  .animate('3s', { opacity: 1 });
```

**Comment by pvdz** [comment]
Maybe it was fixed. I'm sure it didn't work for me. But good if it does now.
