### ISSUE TITLE
Scheduler & Questions

### ISSUE THREAD

**Issue by iammerrick** [uxebu/bonsai#207]
Sometimes you want to schedule things to happen later in a movie, currently I've implemented a scheduler but I can't help but feel like Bonsai must have something built in?

``` javascript
var Scheduler = {
  queue: {},

  schedule: function(when, what) {
    when = stage.toFrameNumber(when);
    this.queue[when] = this.queue[when] || [];
    this.queue[when].push(what);
  },

  execute: function(frame) {
    var queue = this.queue[frame];

    if (queue) {
      queue.forEach(function(callback) {
        callback.apply(null);
      });
    }
  }
}

stage.on('tick', function(stage, frame) {
  Scheduler.execute(frame);
});


/**
 * After 2 seconds show the asset
 */

Scheduler.schedule('2s', function() {
  asset.attr('opacity', 1);
});
```

Also, is there any way to preload assets like SVGs before passing them into the stage? All the asynchrony is unnecessary in most movies. Sorry to be asking here in an issue, there isn't a mailing list and the IRC room is dead. Thanks for Bonsai I'm loving it.

**Comment by iammerrick** [comment]
Looks like: 

``` javascript
stage.frames({
 "2s": function() {
    asset.attr({ opacity: 1 });
 }
});
```

Correct? Found this action in an orbit demo.

**Comment by iammerrick** [comment]
The above scheduling code doesn't behave as expected, I'm seeing the frame function get called multiple times...

**Comment by iamdustan** [comment]
Hey @iammerrick. Sorry for the mega delay on the response (and thanks for the recommendation on JavaScript Jabber!). Did you ever get your scheduler working?

Without using the `toFrameNumber` bit before, I would assume that the returned frame is absolute from the current frame, and not additive from the point of the call. See https://github.com/uxebu/bonsai/blob/master/src/runner/timeline.js#L162-L195

Especially if you have a set time to your movie, each loop through the movie will call your listener again.

Also, the IRC room has a bit more action these past few days, but overall it’s a lurker’s village. We reply to things whenever we see them, but it’s usually many hours after the asker has left the room.
