### ISSUE TITLE
animation duration ignored

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#21]
`this.bg.animate('10s', {opacity: 100}, {easing: 'cubicInOut'});`

The actual animation takes about one second, not ten. Fwiw, the `onEnd` callback does wait about ten seconds to fire.

**Comment by padolsey** [comment]
Using that easing function (cubicInOut) can make it look like an inactive animation, so maybe that's what you're experiencing.

The animation seems to occur for 10 seconds for me here: http://jsbin.com/ivezer/1/edit

Note that `opacity` is `0..1` not `0..100`.
