### ISSUE TITLE
Strange addChild behavior?

### ISSUE THREAD

**Issue by wolframkriesing** [uxebu/bonsai#218]
If I do the following: 

``` js
var group = new Group().addTo(stage);
group.attr({x: 0, y:0});
var rect = new Rect(100, 100, 100, 100).fill("red").addTo(group);

var group1 = new Group().addTo(stage);
group1.attr({x: 200, y:200});
group1.addChild(rect); 
```

`rect` moves from `group` to `group1`, is that correct behavior? Just suprised me. I guess one child can not be child of two parents, right? :)

**Comment by zinkkrysty** [comment]
For me the behavior you're describing is expected. There is [`path.clone()`](http://docs.bonsaijs.org/module-path.Path.html#clone) in case you want to "copy" the element from one group to another.

**Comment by basecode** [comment]
Please re-open the ticket, in case you still see a problem with the current behavior and please provide an example of what you would expect instead.
