### ISSUE TITLE
textAlign property not working

### ISSUE THREAD

**Issue by eppan** [uxebu/bonsai#221]
It seems that the textAlign property has no influence and text seems to always be aligned from left, and cannot for e.g. be aligned to center of document.

**Comment by basecode** [comment]
Hi and thanks for the feedback! Which version of Bonsai are you using? I don't think the API is available yet at the latest build. I hope we can build a new release very soon.

**Comment by eppan** [comment]
Hi, I'm using 0.4.1 which seem to be the newest build available. Any change getting this fixed, since it is hard to measure the length of a text element to align it properly that way.

**Comment by basecode** [comment]
Looks like we already have `textAlign` support since version 0.4.4. We did a new release anyway. See: https://github.com/uxebu/bonsai/releases/tag/v0.4.5

We also pushed the new version to cdns.

**Comment by klipstein** [comment]
Waiting that cdnjs merges it: https://github.com/cdnjs/cdnjs/pull/2627/files
