### ISSUE TITLE
npm does not install

### ISSUE THREAD

**Issue by elmor34** [uxebu/bonsai#223]
I type :  sudo npm install -g bonsai  but not istalling .

Also npm install for package.json doing the same.

get : 
https://registry.npmjs.org/requirejs/-/requirejs-2.0.6.tgz
glob error { [Error: EMFILE, readdir '/usr/local/lib/node_modules/npm/man/man3/author.3']
  errno: 20,
  code: 'EMFILE',
  path: '/usr/local/lib/node_modules/npm/man/man3/author.3' }
glob error { [Error: EMFILE, readdir '/usr/local/lib/node_modules/npm/man/man3/author.3']
  errno: 20,
  code: 'EMFILE',
  path: '/usr/local/lib/node_modules/npm/man/man3/author.3' }
glob error { [Error: EMFILE, readdir '/usr/local/lib/node_modules/npm/man/man3/bin.3']
  errno: 20,
  code: 'EMFILE',
  path: '/usr/loca...     bla bla

**Comment by timoxley** [comment]
This is not a bonsai issue. You need to increase your EMFILE limit. 

http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me
