### ISSUE TITLE
Rookie Question: How to use variable in the attr?

### ISSUE THREAD

**Issue by slmjkdbtl** [uxebu/bonsai#229]
``` javascript
var color = "#ef6360";

bonsai.run($("#star"), {
    code: function() {
        new Star(30, 30, 20, 5).attr({
            fillColor: color
    }).addTo(stage);
    }
});
```

It doesn't work.

**Comment by iamdustan** [comment]
@Voyga the code inside the `code` key is stringified and passed to a webworker, therefore not having access to the files scope.

**Comment by basecode** [comment]
Additional infos are available here: http://docs.bonsaijs.org/overview/Execution.html
