### ISSUE TITLE
Bitmaps cannot be put beyond right side of viewport

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#23]
I've got a movie where I have a group of an image and some rects. The group is placed entirely beyond the right edge of the viewport. A transformation matrix is applied to mirror the group visually. When I animate it from right to left, it appears as if there's a masking effect going on. The image is static and you get to see more of it. I'd expect the image to gradually move from right-to-left too, like the rest of the group, but that doesn't happen.

When moving the group way to the left (so that the right side of the group is not sticking or beyond the right edge of the viewport) the image suddenly does move. As soon as the group breaks with the right side of the viewport, of course.

This leads me to believe that Bitmaps have an issue with being placed beyond the right side of the screen, probably in conjunction when a transformation matrix is applied to them.

**Comment by pvdz** [comment]
Hm. There was a caching issue and now I'm having a hard time reproducing it ... :/

**Comment by pvdz** [comment]
The issue might actually be related to `scaleX`, instead of `transform`. I'll try to figure out whether I can attach a file somehow...

**Comment by pvdz** [comment]
The issue is webkit only. Opera and firefox do not seem to have a problem with it. Chrome and Chromium do.

**Comment by basecode** [comment]
This is the related (simplified) code fragment, Peter is talking about:

```
new Bitmap(url).attr({
  width: '100%',
  height: '100%'
}).addTo(stage);
```

The problem with this is, that the bitmap is not completely downloaded in the time when the renderer tries to place the image. Therefore also the bounding-box of that image can't be computed properly.

The solution would be to pass an onload-callback as second parameter and add the image to the stage as soon as it is loaded. This would be of course asynchronous and the movie-author needs to take care of the proper movie playback.

```
new Bitmap(url, function(err) {
  this.attr({
    width: '100%',
    height: '100%'
  }).addTo(stage);
});
```

This triggers another question. Where is our Preload-API? :)

**Comment by basecode** [comment]
@qfox Thanks for reporting. I guess this wasn't a bug and we found a solution to the problem. Still sth open?

**Comment by pvdz** [comment]
Nope, cheers
