### ISSUE TITLE
Bitmap getComputed() reports 0

### ISSUE THREAD

**Issue by wolframkriesing** [uxebu/bonsai#3]
The computedWIdth() of images currently reports 0, see example below

``` js
new bonsai.Bitmap('http://uxebu.com/media/img/team/padolsey.jpg', function() {
    stage.addChild(this);
    alert(this.getComputed('width') +' ; '+ this.getComputed('height'));
  }
);
```

**Comment by padolsey** [comment]
With [these changes](https://github.com/uxebu/bonsai/commit/a787642f76477c0d225da4fa1b2daa83b1265bc7) this should now work. The getComputed method returns natural-width and natural-height.

**Comment by wolframkriesing** [comment]
updated source above, works. thx
