### ISSUE TITLE
Docs are confusing

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#35]
I know, so is the title of this issue.

For instance, check http://docs.bonsaijs.org/module-filter.filter.DropShadow.html

It starts talking about parameter, but doesn't show the finter print of the function at all.

**Comment by padolsey** [comment]
Thanks for reporting this. In the future though can all docs-related issues be reported in the bonsai-docs repo? - https://github.com/uxebu/bonsai-docs

**Comment by pvdz** [comment]
Hah, sorry, didnt know about that repo. Will do
