### ISSUE TITLE
Remove filter

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#36]
Or I'm just blind. How do you remove a filter once you set it through `.attr({filters: new filter.DropShadow(1, 1, 2, 0x000000FF)})`?

Tried `null`,`"none"`,`[]`. None worked. Strings throw errors.

-- edit: tobi said there's a bug so I'm keeping this ticket

**Comment by basecode** [comment]
A filter can be removed with the following signatures 
- `.attr('filters', [])`
- `.attr('filters', undefined)`
- `.attr('filters', null)`
