### ISSUE TITLE
Animating rotation should have direction attr

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#40]
`shape.attr({rotate:Math.PI / 2}).animate({rotate:-Math.PI})` goes counter-clock wise, always. This makes sense from a range point of view, but when animating in a circle, it could be very desirable to be able to tell the animator which direction to rotate into.

(Docs didn't mention anything related to setting this)

**Comment by padolsey** [comment]
I'm not sure if having a direction property would make matters easier. 

IMO it's easier to just specify an animation from 90deg (Math.PI/2) to 180deg (Math.PI) (i.e. not -180deg). So instead of:

``` js
shape.attr({rotation:Math.PI / 2}).animate({rotation:-Math.PI})
```

Do:

``` js
shape.attr({rotation:Math.PI / 2}).animate({rotation:Math.PI})
```
