### ISSUE TITLE
stage.framerate doesnt affect tick event

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#50]
This may be intentional.

Setting `stage.framerate` doesn't affect the rate at which the tick event is called. It does affect the speed of `.animate` though. Either it should do both or neither. I think it'd be nice if it would do both but could understand if it was a read-only property.

**Comment by pvdz** [comment]
By the way. A workaround is to register the tick event many times. Tested it myself! _cough_

**Comment by padolsey** [comment]
Setting it directly will not restart the timer. I would recommend using `stage.setFramerate()` with your intended framerate. This'll set the property and it'll restart the timer.
