### ISSUE TITLE
Cleanup KeyframeAnimation class

### ISSUE THREAD

**Issue by basecode** [uxebu/bonsai#51]
- `options.delay` is not supported
- setSubjects/setSubject could be removed
-  keyframes in seconds seems a little bit confusing

```
var rect = new Rect(0, 0, 200, 200).fill('green').addTo(stage);
var anim = new KeyframeAnimation('1s', {
  '5s': { x: 500 }
});
rect.animate(anim);
```

**Comment by padolsey** [comment]
Not sure what to do about your last point, "keyframes in seconds seems a little bit confusing" ...

Currently you can define the full duration of the of the KeyframeAnimation in the first argument (s, ms, % etc.) and then you can define the individual keyframes using whatever units you want. I, for example, would normally use percent:

``` js
new bonsai.KeyframeAnimation('4s', {
    '0%': {x: 0, y: 0},
    '25%': {y: 0, x: 400},
    '50%': {x: 400, y: 400},
    '75%': {x: 0, y: 400},
    '100%': {x: 0, y: 0}
});
```

This is intuitive.

And I think it's okay to also have the option of defining the keyframes in seconds/milliseconds too. 

We can discuss removing that feature but we can keep it for "power users" and just not recommend it in the docs. Up for discussion.

**Comment by basecode** [comment]
+1 I would also encourage users to use percent values.

**Comment by basecode** [comment]
Current status:

> options.delay is not supported

This is a bug and still open.

> setSubjects/setSubject could be removed

removed in #75

> keyframes in seconds seems a little bit confusing

we keep them, but we encourage users to use percent values or `from/to`

**Comment by padolsey** [comment]
Are we supporting `options.delay`? Where is that specified?

**Comment by basecode** [comment]
@padolsey Meanwhile the KeyframeAnimation class supports `delay`, right?

**Comment by padolsey** [comment]
Yep.
