### ISSUE TITLE
Position arguments of circle should be relative

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#54]
When I do `new Circle(x,y,50).attr({x:a,y:b})` the values `x` and `y` (the parameters for `Circle`) will be ignored. I would expect those to be coordinates relative to the position of the circle, much like a `.moveTo` before actually drawing the circle.

**Comment by padolsey** [comment]
This seems intuitive to me. With the `attr` call you are overwriting the x and y values you previously set.

**Comment by davidaurelio** [comment]
We had it like @qfox suggests in the very beginning. Everybody was confused because rotation etc. behaved unexpectedly

**Comment by pvdz** [comment]
Ok, weird.

**Comment by padolsey** [comment]
Can this be closed?

**Comment by pvdz** [comment]
I suppose
