### ISSUE TITLE
Normalize touchId

### ISSUE THREAD

**Issue by pvdz** [uxebu/bonsai#58]
Currently with multi touch events you get a touchId which is something like 3326568163 in my example. How can I tell whether this is the first or second finger? Or ninth?

**Comment by padolsey** [comment]
The `touchId` is taken straight from the `domEvent.identifier` value. AFAIK this uniquely identifies the finger across all touch sessions, so you'll never get the same ID twice. To know how many fingers are down, I would do something like:

``` js
var down = 0;

stage.on('multi:pointerdown', function(e) {
  ++down
});
stage.on('multi:pointerup', function(e) {
  --down
});
```

Or, keep a map of the IDs you receive with their current down states. You could also keep them in an array and remove from the array on `pointerup` meaning that the array length will always be equal to the number of fingers.

**Comment by pvdz** [comment]
Okay that makes sense (bonsai could track the number of fingers held, but not sure if that's really useful anyways since you'll want to track specific touches anyways). Should add this to the docs. Will file ticket there.
