### ISSUE TITLE
getComputed

### ISSUE THREAD

**Issue by basecode** [uxebu/bonsai#74]
I was missing a method to get the bounding box of a DisplayObject. I saw that we're supporting `getComputed` instead, which has a even richer API and can return e.g. the "right" or "bottom" offset. But it still doesn't return the bounding box, which is supposed to return an object like `{x, y, width, height}`.
@davidaurelio proposed a new paramater `box` that can be passed to `getComputed`. I would love to field 2 other parameter names. See the list. Would do you like best?
- `getComputed('box')`
- `getComputed('bbox')`
- `getComputed('boundingbox')`

**Comment by padolsey** [comment]
I thought that's what `getComputed('size')` does?

**Comment by padolsey** [comment]
Here: https://github.com/uxebu/bonsai/blob/master/src/runner/path/path.js#L1125-1130

**Comment by davidaurelio** [comment]
Yes, `'size'` does it. My proposal was to alias it with `'box'` if that’s more familiar

**Comment by basecode** [comment]
I think `'size'` is supposed to return `{width:x, height:x}` and not the offset, position or bounding box.. Just the size.

**Comment by basecode** [comment]
I propose the following return values:

`getComputed('size')` => `{width:0, height:0}`
`getComputed('position')` => `{x:0, y:0}`
`getComputed('box')` => `{x:0, y:0, width:0, height:0}`

Maybe also `right`, `bottom`. I would remove `left` and `top` b/c we already have `x` and `y`, which is also known from `attr()`.

**Comment by klipstein** [comment]
I like @basecode's proposal, but would not add `right` and `bottom`, because this could be calculated easily from `x`/`y`/`width`/`height`.

**Comment by davidaurelio** [comment]
- width and height are actually calculated from left and right, top and bottom: https://github.com/uxebu/bonsai/blob/master/src/runner/path/path.js#L1144-1145
- “left” and “top” are named as such to stress their relation to “bottom” and “right”

While I am totally open to discuss misleading naming (e.g. rename “size” to “box” or similar), I’m against making things more complicated and provide less information that we can, just because the users could calculate it themselves.

What’s the point in having separate “size” and “position” keys if “box” would give users everything? Why leave things out we can calculate easily?

**Comment by basecode** [comment]
> While I am totally open to discuss misleading naming

Cool, because "top" is not a "size".

> What’s the point in having separate “size” and “position” keys if “box” would give users everything?

Okay, I'm fine with "box".

> Why leave things out we can calculate easily?

Keep them in. `getComputed('offset') // {top:0, right:0, bottom:0, left:0}` But I don't see why we want to encourage users to use `getComputed('left')` _and_ `attr('x')`. What's the reason?

**Comment by klipstein** [comment]
@davidaurelio @basecode I'm also fine with just having `box` with precalculated left, right, top and bottom. If `x` and `y` is used everywhere we should also include `x = left` and `y = top`.

**Comment by iamdustan** [comment]
The current implementation doesn’t seem to take an elements scaling into account. Should scale be included in the returned 'box' or  is that something the end user can easily compute?

Also, to consider is how that will interact with non-svg renderers in the future.

**Comment by iamdustan** [comment]
Also, do we care about rounding issues? Just tested it on a scaled Rect and had this returned:

```
{
  bottom: 245.5,
  height: 100,
  left: 117.99999999999996,
  right: 217.99999999999994,
  top: 145.5,
  width: 99.99999999999999
}
```

**Comment by davidaurelio** [comment]
> The current implementation doesn’t seem to take an elements scaling into account.

Good catch, @iamdustan. Transformations, in general, are not taken into account.

I’d suggest, that getting computed values from an element shouldn’t take _its own_ transformation into account, because it happens “afterwards”. But container objects should take the transformations of all of their children into account, because it affects the dimensions of the container.

I’d suggest to change the implementations of `getComputed(type)` as following:

``` js
// getComputed for objects consisting of points:
function getComputed(type, matrix) {
  var points = this.points.map(matrix.transformPoint, matrix);
  for (var i = 0, point; (point = points[i]); i += 1) {
    // …
  }
  // …
}
```

``` js
// getComputed for containers:
function getComputed(type, matrix) {
  var children = this.children();
  for (var i = 0, child; (child = children[i]); i += 1) {
    child.getComputed(type, matrix.concat(child.attr('matrix')));
  }
  // …
}
```

**Comment by davidaurelio** [comment]
> Also, do we care about rounding issues? Just tested it on a scaled Rect and had this returned:

Does it feel too wrong? I’m not sure whether we can or should solve all the problems related to floating point numbers. We could switch to a fixed-point based implementation to get rid of these. But this means bigger API changes, since we’d need to use integers internally and hide that from everybody else.

**Comment by iamdustan** [comment]
Two additional DOM methods that exist for this to reference:

`SVGElement.getBox()`: http://www.w3.org/TR/SVG/types.html#__svg__SVGLocatable__getBBox
`Element.getBoundingClientRect()`: https://developer.mozilla.org/en-US/docs/DOM/element.getBoundingClientRect

In comparison to the current `getComputed('size')` method these are the returned results for a `Circle` that has been transformed with the following matrix: `matrix(1.6600000000000006,0,0,1.3300000000000003,187,206)`:

``` javascript
// el.getComputed('size')
{
  bottom: 256
  height: 100
  left: 137
  right: 237
  top: 156
  width: 100
}

// el.getBBox()
{
  height: 100.00000762939453
  width: 100.00001525878906
  x: -50.0000114440918
  y: -50.00000762939453
}

// el.getBoundingClientRect()
{
  bottom: 400
  height: 133
  left: 280.8999938964844
  right: 446.8999938964844
  top: 267
  width: 166
}
```

I think that this BBox implementation is quite unintuitive, thought the `getBoundingClientRect` is most useful. This could extend @basecode’s implementation to the following:

`getComputed('size')` => `{width:0, height:0}`
`getComputed('position')` => `{x:0, y:0}`
`getComputed('box')` => `{x:0, y:0, width:0, height:0}`
`getComputed('rect|boundingRect')` => `{x:0, y:0, width:0*this.attr('scaleX'), height:0*this.attr('scaleY')}`

**Comment by iamdustan** [comment]
@davidaurelio as a user of the library, the floating point numbers aren’t that much of a concern; especially seeing as the default browser (chrome) behavior is to leave the floating digits as are. Having the matrix transformations as it applies to how the current element actually displays on screen is much more of an issue. I don’t know if the effort of change inside the library is worth it for a difference of `0.000000000000003`.
