### ISSUE TITLE
`Make test` as a non uxebu-er

### ISSUE THREAD

**Issue by iamdustan** [uxebu/bonsai#77]
I’m trying to dig deep into bonsai, but can’t run `make test` seeing as I don’t have access to https://github.com/uxebu/ci-tools from https://github.com/uxebu/bonsai/blob/master/Makefile#L14 :(

**Comment by davidaurelio** [comment]
@iamdustan thanks for reporting. You are correct, the makefile is tailored to our CI server. We should make that a little friendlier.

To run the unit tests, you can also open [test/runner.html](https://github.com/uxebu/bonsai/blob/master/test/runner.html) in your browser to run unit tests. Unfortunately, the test coverage of components varies between rough and very good.

**Comment by iamdustan** [comment]
Closed by #78
