### ISSUE TITLE
Event passing between page context and movies

### ISSUE THREAD

**Issue by iamdustan** [uxebu/bonsai#79]
@davidaurelio I’m told your the man for this.

Currently, the only way to pass events inside a movie back to the parent page and vice versa is through the `sendMessage` method. Behind the scenes I presume this will be the path things will need to travel through (for iframe/webworker communication).

Example: https://gist.github.com/3756383

Having to pass user events back and forth this way is suboptimal though. It would be much more intuitive to just emit events and have it captured at each level.

Example: https://gist.github.com/744cf037755422eb888c

**Comment by davidaurelio** [comment]
Thank you for the input. I can see your point and agree that the current situation is not ideal.

For a couple of reasons, I hesitate to connect _main page_ and _stage_ (within the bonsai environment) to a universal emitter.
- I have the impression that if users emit an event on either of the two, they usually intend to communicate something to the other side. A connected event emitter would create the need to differentiate between senders. Say, somebody wants to send `'message'` events from _main page_ to _stage_ and vice-versa, listeners on both sides would need to differentiate. This would probably happen by using two different event types, e.g. `'stage-message'` and `'page-message'`.
- While there are not many events emitted on the _stage,_ four of them could cause significant overhead if also sent to the _main page_: 
  - `'exitFrame'` is fired for each frame and probably of little interest on the _main page_ in many cases. 
  - `'pointermove'` (i.e. `'mousemove'` and `'touchmove'` events) are already piped from _main page_ to the _stage_ and would need to be sent back.
  - `'render'` is emitted for every render cycle (not necessarily the same as a frame)
  - `'submoviesAdvanced'` is emitted in every frame when all sub movies are advanced.

This might be trivial locally (not sure), but we also want to support a remote node server running a bonsai movie.

We still might consider doing this, but we’ll need some time to benchmark and evaluate the results.

If I’ve understood you correctly, the most tedious thing about `sendMessage(data)` is the fact that it is uncategorized, i.e. your message listeners need to branch according to message types. We have the same impression and were already considering to change it to `sendMessage(type, data)`, which would emit a `'message:<type>'` event on the other side.

This is not meant to be implemented _instead_ of your “universal emitter” idea, but could ease the pain for the short term.

Your example would become:

``` js
// main.js
var _stage = document.getElmenetById('stage'),
    stage = bonsai.run(_stage, 'movie.js');

stage.on('message:pointer-up-on-red-square', function () {
  console.log('user-event', arguments);
})
```

``` js
// movie.js
var square = new Rect(0,0,100,100)
square.fill('red')

square.on('pointerup', function (e) {
  stage.sendMessage('pointer-up-on-red-square', e)
})
```

**Comment by klipstein** [comment]
@davidaurelio what do you think of providing a `stage.onMessage` and probably rename `stage.sendMessage` to `stage.emitMessage`, so that it is aligned with `on` / `emit`?

``` js
// main.js
stage.onMessage('pointer-up-on-red-square', function(){});
// movie.js
stage.sendMessage('pointer-up-on-red-square', data);
// or
stage.emitMessage('pointer-up-on-red-square', data);
```

**Comment by klipstein** [comment]
Also see #19 and uxebu/bonsai-docs#20.

**Comment by iamdustan** [comment]
Taking care of uxebu/bonsai-docs#20 would close the initial intent of this issue for me.

I think that the current implementation of `sendMessage`, `on('message')` works once you know it’s there and how it works, though the possibility to declare the `type` with the first argument discussed here would be much more optimal.

Would it be better to alias of `postMessage` and `onmessage` to more closely mimic the [web worker api](https://developer.mozilla.org/en-US/docs/DOM/Using_web_workers) or try to keep inline with bonsai itself with @klipstein’s suggestion?

**Comment by iamdustan** [comment]
Closing this thanks to #95.
