### ISSUE TITLE
A method to tear down what `bonsai.run` sets up

### ISSUE THREAD

**Issue by iamdustan** [uxebu/bonsai#87]
Is there an equivalent of `bonsai.destroy(stage)` to tear down everything that `bonsai.run(stage, movie)` sets up?

I would imagine it would be responsible for removing event handlers, cleaning up the DOM, and generally just destroying all trace of it’s existence.

For long running applications that load up entirely different `movies` throughout it’s lifespan, I would imagine that there would be some memory issues without being able to do a full clean up.

**Comment by pvdz** [comment]
You could you use `movie.destroy()`, where `movie` is the object that `bonsai.run` returns. Or was that what you meant by `bonsai.destroy`?

**Comment by iamdustan** [comment]
That is what I meant. Didn’t realize it already existed.

Is that anywhere in the documentation?

**Comment by pvdz** [comment]
Funny you should mention that ;)

https://github.com/uxebu/bonsai-docs/issues/19

**Comment by iamdustan** [comment]
Haha. Word. That works for me!
