### ISSUE TITLE
sendMessage in runner/stage.js not used?

### ISSUE THREAD

**Issue by nonken** [uxebu/bonsai#98]
It seems that the sendMessage method is dead code. Can someone confirm so we can remove?

**Comment by davidaurelio** [comment]
This is for user events. It triggers a 'message' event on “the other side”.

``` js
// within the bonsai movie
stage.on('message', function(message) { /*…*/ });

// on the main page
var movie = bonsai.run(/*…*/);
movie.sendMessage({some: 'very', important: 'data'});
```

``` js
// on the main page
var movie = bonsai.run(/*…*/);
movie.on('message', function(message) { /*…*/ });

// within the bonsai movie
stage.sendMessage({some: 'very', important: 'data'});
```

The API will even be enhanced by #95, so throwing out is not an option.

**Comment by pvdz** [comment]
@nonken we're using that in our new code to send messages from the runner to the window and back ;)

**Comment by davidaurelio** [comment]
Did you use a code coverage tool to find out? We haven’t had any tests yet, but they will be added by mentioned pull request.

**Comment by nonken** [comment]
oups - thx for clarifying this :) I just wanted to understand the messages being sent during startup and logged out sendMessage first which never fired..
